Check if {nix,home-manager} already exist before fresh installing

diff --git a/renvctl b/renvctl
--- a/renvctl
+++ b/renvctl
@@ -60,15 +60,37 @@ parse_args() {
   command="$1"
 }
 
+command_exists() {
+  local command="$1"
+
+  if [ "$(command -v "${command}")" ]; then
+    log "${command}: Found"
+    return 0
+  else
+    log "${command}: Not found in PATH"
+    return 1
+  fi
+}
+
 nix() {
-  log "Installing nix & home-manager"
+  if ! command_exists "nix"; then
+    log "Installing nix"
 
-  curl -L https://nixos.org/nix/install | sh
+    curl -L https://nixos.org/nix/install | sh
 
-  nix-channel --add https://github.com/nix-community/home-manager/archive/release-21.05.tar.gz home-manager
-  nix_update
+    nix-channel --add https://github.com/nix-community/home-manager/archive/release-21.05.tar.gz home-manager
+    nix_update
+  else
+    log "nix alredy installed"
+  fi
 
-  nix-shell '<home-manager>' -A install
+  if ! command_exists "home-manager"; then
+    log "Installing home-manager"
+
+    nix-shell '<home-manager>' -A install
+  else
+    log "home-manager already installed"
+  fi
 }
 
 nix_update() {
